[package]
name="confidential_licensing_agreement"
type="bin"
authors = ["masaun"]
compiler_version = ">=0.31.0"
version = "0.0.1"  # This will be used in the build.sh in the form of the $VERSION

[dependencies]
# ZK-kit
binary_merkle_root = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "merkle-trees-v0.0.1", directory = "packages/merkle-trees" }
ecdh = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "ecdh-v0.0.1", directory = "packages/ecdh" }
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }

# Openbanking.nr
openbanking_verifier = { tag = "main", git = "https://github.com/attested-frontiers/openbanking.nr-circuit", directory = "./lib" }